### ISSUE TITLE
[core] Touch monitor emits mouse events on desktop

### ISSUE THREAD

**Issue by al1-ce** [raysan5/raylib#3028]
---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
I have touch monitor, on web (in examples) multitouch was successfully recognising inputs (up to 8 points) as such, but as soon as I've tried it on desktop it didn't work, but instead was seen as gesture & mouse input

### Environment
Desktop Arch Linux on X11

### Issue Screenshot
None

### Code Example
https://github.com/raysan5/raylib/blob/master/examples/core/core_input_multitouch.c

**Comment by raysan5** [comment]
@al1-ce I'm afraid desktop multi-touch is not supported by GLFW library used by raylib on desktop for inputs management. When compiling for web, raylib uses browser capabilities, that have a very good support for multi-touch inputs.

**Comment by al1-ce** [comment]
I am absolutely aware of this
Had a whole deep dive research since kitty term uses glfw too

And as I've stated in [kitty's issue](https://github.com/kovidgoyal/kitty/issues/984) rn there's only X11 pending since win, mac and wayland are basically ready

**Comment by chriscamacho** [comment]
can you check xinput its likely that your monitor could be reporting touch events as mouse events, depending on how its configured

use xinput list to check the device id number
then xinput test <id number>

see what type of events you get it might give you a clue as to what is going on...

**Comment by al1-ce** [comment]
Ok, I've tested it with xinput
output of `xinput test 8`
```
button press   1 a[0]=60646 a[1]=20720 
motion a[0]=60646 a[1]=20704 
motion a[0]=60646 a[1]=20720 
motion a[0]=60643 a[1]=20720 
motion a[0]=60643 a[1]=20720 
button release 1 a[0]=60643 a[1]=20720
```
It seems to just send plain mouse motions, but
output of `xinput test-xi2 8` is
```
EVENT type 18 (TouchBegin)
    device: 8 (8)
    detail: 57
    flags: emulating
    root: 4528.44/710.17
    event: 620.44/434.17
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
        0: 60320.25
        1: 24240.63
    windows: root 0x1e4 event 0x2c00001 child 0x2c00001
...
EVENT type 20 (TouchEnd)
    device: 8 (8)
    detail: 60
    flags:
    root: 4413.74/817.05
    event: 505.74/541.05
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
        0: 58792.47
        1: 27888.57
    windows: root 0x1e4 event 0x2c00001 child 0x2c00001
```

My guess is that as of yet GLFW primarily supports xinput and not xinput2, even though I saw xi2 imports in some of source files
